### ISSUE TITLE
discussion/structure for storing models and interfaces

### ISSUE THREAD

**Issue by Diegiwg** [VacuumORG/forum_vacuum_front#38]
Como será padronizado a estrutura para os Modelos e Interfaces do projeto?

Por exemplo, no PR #29 precisei criar uma estrutura para tipagem do objeto esperado como `body` da request.

No momento, esse modelo existe apenas dentro do arquivo dessa rota, porém, esse pode ser um modelo re-aproveitável, na medida que ele descreve as informações necessárias para fazer Login.

Procurei por outro exemplo em nossa base de código, e no PR #31 foi criada a interface `SignUpAvatarProps`, que também poderia ser útil em outros locais da aplicação.

Enfim, acredito que padronizar o local, e se vamos usar `class`, `type` ou `interface` para criar nossas anotações de tipo, seja uma oportunidade de melhorar nosso ambiente de desenvolvimento.

**Comment by RickChaves29** [comment]
É um ótimo questionamento, acho interessante vocês criarem uma pasta no raiz do projeto chamada `models` ou `dtos` 
E lá dentro ter todas as estruturas de dados  que vão precisar, poderem  seguir o padrão ex:` DataBody` ou `DataModel` ou `DataDTO`
Usando penas `type` ou `interface`  nada de `class`

**Comment by Diegiwg** [comment]
Gosto da pasta ´model´.
