### ISSUE TITLE
[DISCUTIR] Workflow do sistema de rotas protegidas

### ISSUE THREAD

**Issue by Diegiwg** [VacuumORG/forum_vacuum_front#66]
# [DISCUTIR] Workflow do sistema de rotas protegidas

O desenvolvimento de rotas está parado, pois não temos como continuar a escrever rotas que sabemos 'serem protegidas', sem primeiro definir como vamos proteger as mesmas.

## O que já sabemos

- A gestão de Usuários, incluindo o processo de Criar e fazer Login, é gerido automaticamente pelo Módulo de Auth do Supabase.
- Ações do módulo Auth devolvem como response, as informações do usuário, incluindo o Profile dele. E o mais importante, uma Session JWT.
- A Session JWT possui um Token, o refresh_token, que pode ser posteriormente utilizado para validar se a Session é ou não valida.

### Login

Teremos uma rota, provavelmente `auth/login`, que irá receber via `$POST` o objeto composto por `{email, password}`.
Dai, verificamos se os dois campos são strings, verificamos se o e-mail é valido, e mandamos a Request para o Supabase.
Verificamos a resposta, devolvendo o erro se existir.
No caso esperado, devolvemos o seguinte objeto `{session_token:string, data:$userProfile}`.

> Nesse ponto, se espera que o front armazene o `session_token` para posterior utilização nas requisições de rotas protegidas.

### Rotas protegidas

Todas as rotas protegias, estarão esperando com as informações especificas do contexto, o objeto `session_token`.
A primeira verificação a ser feita é se o `session_token` é valido, utilizando o Supabase.
Caso seja invalido, um erro deve ser acionado e a requisição finalizada.
No final de todo o trâmite da rota específica, será devolvido o objeto `{session_token:string, data:any}`.

> Nesse ponto, se espera que o front armazene o `session_token` para posterior utilização nas requisições de rotas protegidas.

### Possível recurso de implementação

Criar um `decorator`, que será o guarda das rotas protegidas. Além de verificar o `session_token`, podemos utilizar o `decorator` para filtrar os `verbos http` que queremos permitir na rota.

A exemplo:

```typescript

@protected('GET')
export async funtion handler(req: NextApiRequest, res: NextApiResponse) { ... }

```

> Vamos resolver isso até dia 14.05, para não atrasar demais.

**Comment by Luciano-Ferreira** [comment]
Olha apoio a idéia do Decorator imagino que será como o @UseGuards do NestJS, porém eu não sei fazer, e estou aqui pra aprender.

**Comment by Diegiwg** [comment]
Bom, utilizar um decorator não vai funcionar. Pois no Typescript, eles não dão suporte a modificar uma função.
