### ISSUE TITLE
[Informações] Lista de Rotas da API

### ISSUE THREAD

**Issue by Diegiwg** [VacuumORG/forum_vacuum_front#68]
# Lista de Rotas da API

## Login (Auth)

|Verbos|Protegida|Rota|Descrição|
|-|-|-|-|
|POST|Não|/api/v1/auth|Esta rota é usada para autenticação (login) do usuário.

## Perfil

|Verbos|Protegida|Rota|Descrição|
|-|-|-|-|
|GET|Não|/api/v1/profiles/list|Esta rota retorna uma lista de perfis.
|POST|Não|/api/v1/profiles/create|Esta rota é usada para criar um novo perfil (usuário).
|GET|Sim|/api/v1/profiles/$id:profile/get|Esta rota retorna informações sobre um perfil específico.
|GET|Sim|/api/v1/profiles/$id:profile/topics/list|Esta rota retorna uma lista de tópicos criados por um perfil específico.
|POST|Sim|/api/v1/profiles/$id:profile/topics/create|Esta rota é usada para criar um novo tópico em um perfil específico.
|PATCH|Sim|/api/v1/profiles/$id:profile/topics/$id:topic/edit|Esta rota é usada para editar um tópico existente criado por um perfil específico.
|DELETE|Sim|/api/v1/profiles/$id:profile/topics/$id:topic/delete|Esta rota é usada para remover um tópico existente criado por um perfil específico.
|GET|Sim|/api/v1/profiles/$id:profile/comments/list|Esta rota retornar uma lista de todos os comentários feitos por um perfil específico. 

## Tópicos

|Verbos|Protegida|Rota|Descrição|
|-|-|-|-|
|GET|Não|/api/v1/topics/list|Esta rota retorna uma lista de todos os tópicos.
|GET|Não|/api/v1/topics/$id:topic/get|Esta rota retorna informações sobre um tópico específico.
|GET|Não|/api/v1/topics/$id:topic/likes/get|Esta rota retorna o número de curtidas para um tópico específico.
|PATCH|Sim|/api/v1/topics/$id:topic/likes/increase|Esta rota é usada para aumentar o número de curtidas para um tópico específico
|PATCH|Sim|/api/v1/topics/$id:topic/likes/decrease|Esta rota é usada para diminuir o número de curtidas para um tópico específico.
|GET|Não|/api/v1/topics/$id:topic/comments/list|Esta rota retorna uma lista de todos os comentários em um tópico específico.
|POST|Sim|/api/v1/topics/$id:topic/comments/create|Esta rota é usada para criar um novo comentário em um tópico específico.
|GET|Sim|/api/v1/topics/$id:topic/comments/$id:comment/get|Esta rota retorna informações sobre um comentário específico em um tópico.
|PATCH|Sim|/api/v1/topics/$id:topic/comments/$id:comment/edit|Esta rota é usada para editar um comentário existente em um tópico específico.
|DELETE|Sim|/api/v1/topics/$id:topic/comments/$id:comment/delete|Esta rota é usada para remover um comentário existente em um tópico específico.

## Tags

|Verbos|Protegida|Rota|Descrição|
|-|-|-|-|
|GET|Não|/api/v1/tags/list|Esta rota retorna uma lista de todas as tags.
|GET|Não|/api/v1/tags/$id:tag/list|Esta rota retorna uma lista de tópicos associados a uma tag específica.

**Comment by Diegiwg** [comment]
## O que gostaria com essa Issue

Primeiro, gostaria que vocês do @VacuumORG/backend-team discutissem se essas são todas as rotas necessárias. E se está correta a configuração de Verbo e Proteção de cada uma.

Segundo, caso tenham discordância sobre a anotação das rotas, deixem suas propostas nos comentários.

Pessoal do @VacuumORG/frontend-team, se vocês tiverem mais algum `dado` que não está sendo exposto aí nessa lista, podem por aqui nos comentários, que iremos discutir como incluir eles em uma rota ou cria uma própria.

## Sobre as rotas

Quase todas as que já temos, que não são muitas, não estão implementando os recursos do PR #67.

Assim, devemos refatorar estas existentes, e criar as demais.

Temos um prazo para o projeto na totalidade até o dia **25/05/2023**, então, estamos bem próximos de estourar este prazo.

**Comment by josegnilton** [comment]
Acredito que tudo certo pela parte do back, precisamos da análise do front pra saber se as informações dispostas estão corretas e suficientes.

**Comment by RickChaves29** [comment]
Todas as rotas então muito bem definidas, só não vi utilidade para as seguintes rotas 
| verbo| rota|
| ----------- | ----------- |
| PATCH | /api/v1/topics/$id/views/decrease |
| GET  | /api/v1/topics/$id/views/get|
| GET| /api/v1/topics/$id/likes/get|

estou levando em conta que esses dados já vem com os dados do tópico, é para qual motivos precisamos remove visualizações.
Fora isso está coerente e podem seguir dessa forma

**Comment by Diegiwg** [comment]
É verdade, me passei aqui. Otimo, menos rotas a codar.

**Comment by lucasgrocha** [comment]
Eu corrigi algumas rotas para ficarem mais padrão "rest" :shipit: 

# Mudanças:
- Removi as seguintes rotas 
  - `/list`
  - `/get`
  - `/create`
  - `/delete`
  - `/edit`
- Também removi uma rota que estava com função duplicada, mas perdi qual era por usar o editor :sweat_smile: 

# Por que?

Em REST, nós trabalhamos em cima dos recursos e utilizamos os verbos HTTP para delegar como cada recurso se comportará, portando é experado que ao chamar `/profiles` uma lista de perfis seja retornada, o mesmo se aplica para os outros recursos

- `/list`
É esperado que ao chamar uma rota apenas com o nome do recurso, TODOS os dados sejam retornados, não há necessidade de dizer que queremos uma lista
  - É importante observar que também queremos ter um controle para não sobrecarregar o banco, portando é sempre uma boa utilizar o esquema de paginação

- `/get`
É esperado que ao passar um $id para a o recurso, os dados que pertencem à tal ID sejam retornados. 

- `/create`
É esperado que ao chamar o recurso com o verbo POST o backend faça a criação do recurso para a gente no banco de dados, o POST é sempre utilizado para tudo que terá um efeito "server-side"

- `/delete`
Ao deletar, não há necessidade de usar uma rota `/delete` porque já estamos utilizando o verbo DELETE para isso

- `/edit`
Para editarmos X recurso, não precisamos dizer na rota que queremos, apenas utilizar o verbo HTTP correto, nesse caso, o `PATCH` ou `UPDATE`


# Aqui estão todas as rotas + as rotas que foram corrigidas

## Perfil

Verbos | Protegida | Rota | Descrição
-- | -- | -- | --
GET | Não | /api/v1/profiles | Esta rota retorna uma lista de perfis.
POST | Não | /api/v1/profiles | Esta rota é usada para criar um novo perfil (usuário).
GET | Sim | /api/v1/profiles/$id:profile | Esta rota retorna informações sobre um perfil específico.
GET | Sim | /api/v1/profiles/$id:profile/topics | Esta rota retorna uma lista de tópicos criados por um perfil específico.
POST | Sim | /api/v1/profiles/$id:profile/topics | Esta rota é usada para criar um novo tópico em um perfil específico.
PATCH/UPDATE | Sim | /api/v1/profiles/$id:profile/topics/$id:topic | Esta rota é usada para editar um tópico existente criado por um perfil específico.
DELETE | Sim | /api/v1/profiles/$id:profile/topics/$id:topic | Esta rota é usada para remover um tópico existente criado por um perfil específico.
GET | Sim | /api/v1/profiles/$id:profile/comments | Esta rota retornar uma lista de todos os comentários feitos por um perfil específico.

## Tópicos
Verbos | Protegida | Rota | Descrição
-- | -- | -- | --
GET | Não | /api/v1/topics | Esta rota retorna uma lista de todos os tópicos.
GET | Não | /api/v1/topics/$id:topic | Esta rota retorna informações sobre um tópico específico (incluindo os likes).
PATCH | Sim | /api/v1/topics/$id:topic | Esta rota é usada para aumentar o número de curtidas para um tópico específico (precisa passar o parâmetro certo para aumentar)
POST | Sim | /api/v1/topics/$id:topic/likes | Esta rota é usada para diminuir o número de curtidas para um tópico específico. (precisa passar o parâmetro certo para diminuir)
GET | Não | /api/v1/topics/$id:topic/comments | Esta rota retorna uma lista de todos os comentários em um tópico específico.
POST | Sim | /api/v1/topics/$id:topic/comments | Esta rota é usada para criar um novo comentário em um tópico específico.
GET | Sim | /api/v1/topics/$id:topic/comments/$id:comment | Esta rota retorna informações sobre um comentário específico em um tópico.
PATCH/UPDATE | Sim | /api/v1/topics/$id:topic/comments/$id:comment | Esta rota é usada para editar um comentário existente em um tópico específico.
DELETE | Sim | /api/v1/topics/$id:topic/comments/$id:comment | Esta rota é usada para remover um comentário existente em um tópico específico.


## Tags
Verbos | Protegida | Rota | Descrição
-- | -- | -- | --
GET | Não | /api/v1/tags | Esta rota retorna uma lista de todas as tags.
GET | Não | /api/v1/tags/$id:tag | Esta rota retorna uma lista de tópicos associados a uma tag específica.
