### ISSUE TITLE
fix: botão voltar do modal de cadastro

### ISSUE THREAD

**Issue by pimbrizi** [VacuumORG/forum_vacuum_front#89]
Somente o icon está clicável. É interessante que a palavra _voltar_ também seja.

**Comment by Diegiwg** [comment]
Concordo, é muito estranho ter que clicar no ícone. Minha mão sempre vai direto no texto rs

**Comment by dayanecol** [comment]
Corrigido! Aguardando a aprovação do PR para fechar esse issue.
